---
##############################################################################
# Keycloak Handlers
##############################################################################

- name: restart keycloak
  ansible.builtin.systemd:
    name: keycloak
    state: restarted
    daemon_reload: true
