---
##############################################################################
# Caddy Handlers
##############################################################################

- name: restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
    daemon_reload: true
